-- KPI: performance_canal
-- Pergunta: qual canal está carregando o mês e qual está afundando?
--
-- Canal = TGFCAB.AD_ORIGEM.
-- ATENÇÃO: 27% do faturamento de set/26 está com AD_ORIGEM NULO
-- (R$ 1.716.600,96 em 4.079 notas). Enquanto isso não for corrigido no
-- cadastro, este KPI fica em modo sombra. O bloco SEM_CANAL existe para
-- tornar o buraco visível em vez de escondê-lo.
--
-- Params: {{CODEMP}}

WITH TOPFAT AS (
  SELECT CODTIPOPER FROM TGFTOP
   WHERE ATUALCOM = 'C' AND NVL(AD_INSEREDASH,'N') = 'S'
),
BASE AS (
  SELECT NVL(CAB.AD_ORIGEM,'(SEM CANAL)') AS CANAL, CAB.DTNEG, CAB.VLRNOTA
    FROM TGFCAB CAB /*CC TGFCAB CC*/
   WHERE CAB.STATUSNOTA = 'L'
     AND CAB.CODTIPOPER IN (SELECT CODTIPOPER FROM TOPFAT)
     AND CAB.CODEMP IN ({{CODEMP}})
     AND CAB.CODPARC NOT IN (SELECT CODPARC FROM TSIEMP WHERE CODPARC IS NOT NULL)
     AND CAB.DTNEG >= ADD_MONTHS(TRUNC(SYSDATE,'MM'),-3)
),
POR_CANAL AS (
  SELECT CANAL,
         SUM(CASE WHEN DTNEG >= TRUNC(SYSDATE,'MM') THEN VLRNOTA ELSE 0 END) AS MTD,
         SUM(CASE WHEN DTNEG <  TRUNC(SYSDATE,'MM') THEN VLRNOTA ELSE 0 END)/3 AS MEDIA_3M
    FROM BASE GROUP BY CANAL
),
RANKED AS (
  SELECT CANAL, MTD, MEDIA_3M,
         MTD / GREATEST(TRUNC(SYSDATE)-TRUNC(SYSDATE,'MM')+1,1)
             * TO_NUMBER(TO_CHAR(LAST_DAY(SYSDATE),'DD'))
             / NULLIF(MEDIA_3M,0) * 100 AS PCT
    FROM POR_CANAL
   WHERE MEDIA_3M > 0 AND CANAL <> '(SEM CANAL)'
)
SELECT
  (SELECT ROUND(MIN(PCT),1) FROM RANKED)                       AS PCT_PIOR_CANAL_VS_MEDIA,
  (SELECT CANAL FROM RANKED WHERE PCT = (SELECT MIN(PCT) FROM RANKED)
    FETCH FIRST 1 ROWS ONLY)                                   AS ROTULO,
  (SELECT ROUND(SUM(MTD),2) FROM POR_CANAL WHERE CANAL='(SEM CANAL)') AS VLR_SEM_CANAL,
  (SELECT ROUND(SUM(CASE WHEN CANAL='(SEM CANAL)' THEN MTD ELSE 0 END)
               / NULLIF(SUM(MTD),0) * 100, 1) FROM POR_CANAL)   AS PCT_SEM_CANAL
FROM DUAL
